# Generated by Django 2.2.7 on 2019-11-09 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('origin', models.CharField(max_length=250)),
                ('destination', models.CharField(max_length=250)),
                ('statusCode', models.IntegerField()),
            ],
        ),
    ]
